# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-16.04"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key     = false
  config.ssh.forward_agent  = true

  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
	ansible.verbose     = true
	ansible.install     = true
    ansible.playbook    = "playbooks/vagrant.yml"
  end

  config.vm.network "private_network", ip: "192.168.56.106"
end
